# Site settings
title: Frontend Bucharest
email: fe.bucharest@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bucharest Frontend Developers Community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frontendbucharest.ro" # the base hostname & protocol for your site
facebook_url: https://www.facebook.com/groups/frontend.bucharest

# Build settings
markdown: kramdown
